### ISSUE TITLE
Updates not working

### ISSUE THREAD

**Issue by akatebi** [relayjs/relay-devtools#12] opened 2018-05-20 12:32 UTC
Relay DevTools 1.4.0
On Ubuntu version 18.04 Google Chrome Version 66.0.3359.181 (Official Build) (64-bit). 
Try the official relay-examples todo. On the "updates" tab of the relay-devtools in the browsers relay extensions I only see this message: "Waiting for updates from Relay application" 
It does the same in my own application too.

**Comment by olessavluk** [comment] 2018-05-27 18:15
looks like a duplicate of https://github.com/relayjs/relay-devtools/issues/11

as a temporary workaround you can build and run latest version manually:
```
yarn build:standalone
node lib/standalone/launchApp.js
```

**Comment by avijohnson** [comment] 2018-11-15 20:43
closed with #13

**Closed by avijohnson** 2018-11-15 20:43 UTC

**Comment by tslater** [comment] 2019-10-26 23:00
I've tried npm release and building the latest on master. I'm still stuck on "connecting to relay...". I'm on Relay 7.0.0. Any suggestions?
